In [16]:
#Artificial Neural Networks(ANN)
# 1.Data Pre-Processing

In [1]:
#Import Models
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Importing Datasets
dataset = pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X = dataset.iloc[:,3:13].values
Y = dataset.iloc[:,13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [4]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

In [7]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [6]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [8]:
X = X[:, 1:]

In [12]:
#Training Sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [13]:
X_test

array([[  1.00000000e+00,   0.00000000e+00,   5.97000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.92852670e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.23000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.28702100e+05],
       [  0.00000000e+00,   1.00000000e+00,   7.06000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   7.57322500e+04],
       ..., 
       [  0.00000000e+00,   1.00000000e+00,   5.78000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.41533190e+05],
       [  1.00000000e+00,   0.00000000e+00,   6.50000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.12764800e+04],
       [  1.00000000e+00,   0.00000000e+00,   5.73000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.92950600e+05]])

In [14]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
X_test

array([[ 1.75486502, -0.57369368, -0.55204276, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-0.5698444 , -0.57369368, -1.31490297, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-0.5698444 ,  1.74309049,  0.57162971, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ..., 
       [-0.5698444 ,  1.74309049, -0.74791227, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 1.75486502, -0.57369368, -0.00566991, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 1.75486502, -0.57369368, -0.79945688, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [14]:
#2. Creating ANN
#Import Models
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
#Initialize Neural Networks

In [16]:
classifier = Sequential()

In [17]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))


In [19]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 4s 458us/step - loss: 0.4775 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 3s 373us/step - loss: 0.4262 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 385us/step - loss: 0.4205 - acc: 0.8069
Epoch 4/100
8000/8000 [==============================] - 3s 404us/step - loss: 0.4169 - acc: 0.8252
Epoch 5/100
8000/8000 [==============================] - 4s 502us/step - loss: 0.4152 - acc: 0.8279
Epoch 6/100
8000/8000 [==============================] - 4s 503us/step - loss: 0.4134 - acc: 0.8310
Epoch 7/100
8000/8000 [==============================] - 4s 524us/step - loss: 0.4119 - acc: 0.8329
Epoch 8/100
8000/8000 [==============================] - 4s 515us/step - loss: 0.4109 - acc: 0.8322
Epoch 9/100
8000/8000 [==============================] - 4s 446us/step - loss: 0.4100 - acc: 0.8325
Epoch 10/100
8000/8000 [==============================] - 4s 457us/step - loss: 0.4088 - acc: 0.8335

In [18]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [19]:
cm

array([[954, 641],
       [256, 149]])

In [24]:
1688/2000

0

In [2]:
#84.25%